Automate pypi releases
Quansight/jupyterlab-conda-store pull request #6
Opened 2023-01-21 00:23 UTC by anirrudh

This PR has some work to be done before being merged, namely: 

1) Remove the branches directive while deciding when to trigger the workflow
and
2) Upload to real upload.pypi.org instead of uploading to test.pypi.org, done by modifying the `twine upload` command to pypi instead of testpypi and then additionally swapping the secrets out as well. 

This PR addresses issue #5.

2023-01-23 15:34 UTC, costrouc requested changes

2023-01-23 15:34 UTC, costrouc commented on .github/workflows/build_and_deploy_release.yml
> +        pip uninstall -y "jupyterlab_conda_store" jupyterlab
Why do we need to uninstall?

2023-01-23 17:35 UTC, anirrudh commented on .github/workflows/build_and_deploy_release.yml
> +        pip uninstall -y "jupyterlab_conda_store" jupyterlab
No need, leftover artifact!

2023-01-23 17:36 UTC, anirrudh commented on .github/workflows/build_and_deploy_release.yml
> +        TWINE_USERNAME: ${{ secrets.PYPI_TEST_USERNAME }}
updated

2023-01-23 17:38 UTC, anirrudh commented
Hey @costrouc, the files in the GitHub Actions have been updated accordingly. Once the PR is merged, things will work. In order to prepare this, I've changed the files in this branch to point to main so It will get picked up from there. This PR now uses the same Build Step used on a release and reuses the workflow.

2023-01-23 21:55 UTC, costrouc commented
@anirrudh looks like the CI is failing for releases no? https://github.com/Quansight/jupyterlab-conda-store/actions/runs/3989136574/jobs/6841194500

2023-01-26 17:01 UTC, costrouc approved these changes

2023-01-26 17:02 UTC, merged